config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'

    get 'sessions/new'

    post 'sessions' => 'sessions#create'

    post 'login' => 'sessions#login'

    delete "sessions/:id" => "sessions#destroy"

    get 'groups' => "groups#index"

    post 'groups' => 'groups#create'

    get 'groups/:id' => 'groups#show'

    get 'groups/join/:id' => 'groups#join'

    get 'groups/leave/:id' => 'groups#leave'

    delete 'groups/:id' => 'groups#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :org
end

app/models/org.rb
class Org < ApplicationRecord
  belongs_to :user
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, source: :user

  validates :name, presence: true, length: { in: 5..20 }
  validates :desc, presence: true, length: { in: 10..250 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orgs, through: :memberships, source: :org
  has_many :memberships, dependent: :destroy

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    validates :fname, :lname, presence: true, length: { in: 2..20 }
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def index
        @user = User.find(session[:id])
        @orgs = Org.all
    end

    def create
        @org = Org.new(name: params[:name], desc: params[:desc], user: User.find(session[:id]))
        if @org.save
            Membership.create(user: User.find(session[:id]), org: @org)
            redirect_to '/groups'
        else
            flash[:errors] = @org.errors.full_messages
            redirect_to '/groups'
        end
    end

    def show
        @user = User.find(session[:id])
        @org = Org.find(params[:id])
        @members= @org.users

    end

    def join
        @mem = Membership.new(user: User.find(session[:id]), org: Org.find(params[:id]))
        @mem.save
        redirect_to "/groups/#{params[:id]}"
    end


    def leave
        Membership.find_by(user: User.find(session[:id]), org: Org.find(params[:id])).destroy
        redirect_to "/groups/#{params[:id]}"
    end

    def destroy
        group = Org.find(params[:id]).destroy
        redirect_to "/groups"
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:id] = @user.id
            redirect_to "/groups"
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to "/"
        end

    end

    def login
        if !(User.find_by(email: params[:login_email])).nil?
           @user = User.find_by(email: params[:login_email])
           if @user.authenticate(params[:login_password])
               session[:id] = @user.id
               redirect_to "/groups"
           else
               flash[:errors] = ["Invalid Combination"]
               redirect_to "/"
           end
       else
           flash[:errors] = ["Invalid Combination"]
           redirect_to "/"
       end
    end


    def destroy
        reset_session
        redirect_to "/"
    end

    private
           def user_params
               params.require(:user).permit(:fname, :lname, :email, :password)
           end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/groups/index.html.erb
<h1>Hello <%=@user.fname%> <%=@user.lname%></h1>

<button><a href="/sessions/:id" data-method="delete"> Logout</a></button>

<h3>Here are the organizations you may join:</h3>


<div id="outer" style="display: inline-block;  vertical-align: top; width: 40%">
<% @orgs.each do |org| %>
    <div class="detail" style="margin-left: 20px; border-bottom: black 1px solid; display: block">

        <h4>
            <a href="groups/<%=org.id%>"> <%= org.name %> </a>
            <%if @user.id == org.user.id %>
            - <a href="groups/<%= org.id %>" data-method="delete">Delete Group</a>
            <%end%>
        </h4>


        <p>Members: <%= org.users.count %></p>
        <p><%= org.desc %></p>
    </div>
<% end %>
</div>



<div id="new-org" style="display: inline-block; width: 35%; vertical-align: top; border: black solid 1px; margin-left: 80px; padding: 12px">
    <h4>Create a new organization:</h4>

    <% if flash[:errors] %>
        <% flash[:errors].each do |e| %>
            <p class="error"><%= e %></p>
        <% end %>
    <% end %>

    <form action="/groups" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        Org Name:<input type="text" name="name">
        <br><br>
        Description: <input type="text" name="desc">
        <br><br>
        <input type='submit' value='Create'>
    </form>

</div>

app/views/groups/show.html.erb
<a href="/groups">Dashboard</a>
<a href="/sessions/:id" data-method="delete"> Logout</a>
<br>
<br>
<h3 style="display: inline"><%=@org.name%> - </h3>
<% if @org.user_ids.include?(@user.id) %>
<a href="/groups/leave/<%= @org.id %>"> Leave Org</a>
<% else %>
<a href="/groups/join/<%= @org.id %>">Join Org</a>
<% end %>

<p>Description: <%=@org.desc%></p>

<p>Created by:
    <% if @org.user.id == @user.id %>
        YOU
    <% else %>
    <%=@org.user.fname %> <%=@org.user.lname %>
    <%end%>

</p>
<br>
<p style="font-weight: bold">Members:</p>

<% @members.each do |member|%>
    <p style="margin-left: 20px"> <%= member.fname%> <%= member.lname%> </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROROrg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>